version: "3.5"
services: 
  launcher-backend:
    build:
      context: ./backend
    restart: always
    networks: [app]
    volumes:
     - /home/ubuntu/clusters:/backend/clusters
    secrets:
     - source: mercury-key
       target: /root/.ssh/id_rsa
     - source: openrc
       target: ./backend
  launcher-frontend:
    build:
      context: ./frontend
    restart: always
    networks: [app]
    depends_on: [launcher-backend]
  nginx:
    image: nginx
    restart: always
    depends_on:
    - launcher-backend
    - launcher-frontend
    ports:
    - "443:443"
    networks:
    - app
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf

secrets:
  mercury-key:
    file: id_rsa
  openrc:
    file: ./backend/hgi-openrc.sh
networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.1/24
