version: "3"
services: 
  backend:
    build:
      context: ./backend
    restart: always
    networks: [app]
    ports: ['5000:5000']
    volumes:
    - /home/ubuntu/clusters:/backend/clusters
  frontend:
    build:
      context: ./frontend
    restart: always
    networks: [app]
    ports: ['8080:8080']
    depends_on: [backend]
  nginx:
    image: nginx
    restart: always
    depends_on:
    - backend
    - frontend
    ports:
    - 8000:80
    networks:
    - app
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.1/24
